# syntax=docker/dockerfile:1

FROM python:3

WORKDIR /app/

COPY ./requirements/tests.txt /app/requirements.txt

RUN apt update && apt upgrade -y
RUN python -m pip install --upgrade pip && pip install -r requirements.txt

COPY . /app/
