# syntax=docker/dockerfile:1

FROM python:3

ARG USERNAME=dev
ARG USER_UID=1001
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

WORKDIR /app/

COPY ./requirements/dev.txt /app/requirements.txt

RUN apt update && apt upgrade -y
RUN python -m pip install --upgrade pip && pip install -r requirements.txt

COPY . /app/

USER $USERNAME
