version: "3"

services:
  cli-app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      # Mounts the project folder to '/app'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/app:cached

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
